name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild \
          -project FeriasESF.xcodeproj \
          -scheme FeriasESF \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          build
