name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild \
          -project FeriasESF.xcodeproj \
          -scheme FeriasESF \
          -sdk iphonesimulator \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          build

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: FeriasESF-iOS-App
          path: build/Build/Products/Release-iphonesimulator/
